### ISSUE TITLE
Not working on other languages

### ISSUE THREAD

**Issue by WorldLanguages** [WorldLanguages/FollowersNumberEnabler#2]
If you don't use English as language, the following and followers number will apear in the incorrect place.

**Comment by joker314** [comment]
I'll look into it :)

**Comment by joker314** [comment]
You are searching for the English text -- https://github.com/WorldLanguages/FollowersNumberEnabler/blob/master/script.user.js#L110

Instead, search for the parent element. Also, you don't want to replace the next within (or you will overide it to English), instead you'll want to append.

I'll make a PR when I have some spare time :)

**Comment by joker314** [comment]
I'm working on major changes, including commenting the code much better and indenting better. One thing to note, https://github.com/WorldLanguages/FollowersNumberEnabler/blob/master/script.user.js#L82 you doing the request synchronously. This places a warning in my browser console. In my PR I will use asynchronous requests with callbacks.

**Comment by WorldLanguages** [comment]
I know why it happens. Thanks for helping! :D

**Comment by WorldLanguages** [comment]
And I'm also searching for "Studios I'm following", that is different on other languages, making the code think the "Studios I'm following" row is the "Followers" row

**Comment by WorldLanguages** [comment]
Closed - https://github.com/WorldLanguages/FollowersCountOnProfileMULTILINGUAL
