### ISSUE TITLE
Not working if "Scratch followers number enabled" userscript is also running

### ISSUE THREAD

**Issue by CosmicWebServices** [WorldLanguages/FollowersNumberEnabler#3]
https://github.com/WorldLanguages/isOnline/issues/4

I think you need the other userscript (isOnline) to detect if the other userscript is enabled and if it is enabled have that userscript wait for this userscript to be done.

**Comment by CosmicWebServices** [comment]
btw I am IcyCoder

**Comment by joker314** [comment]
In future, we will try to make our userscripts use `addEventListener` instead of directly assigning an event listening attribute to the window. These problems should be avoided in future, therefore :)
